// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calcT0Wsim1
Rcpp::List calcT0Wsim1(arma::mat& CvSqrt, arma::mat& weight, arma::vec powV, int nperm);
RcppExport SEXP aSPU2_calcT0Wsim1(SEXP CvSqrtSEXP, SEXP weightSEXP, SEXP powVSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type CvSqrt(CvSqrtSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calcT0Wsim1(CvSqrt, weight, powV, nperm));
    return rcpp_result_gen;
END_RCPP
}
// avg_rank
arma::vec avg_rank(arma::vec x);
RcppExport SEXP aSPU2_avg_rank(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(avg_rank(x));
    return rcpp_result_gen;
END_RCPP
}
// calcT0Wsim3
Rcpp::List calcT0Wsim3(arma::mat& CvSqrt, arma::mat& weight, arma::vec powV, arma::vec Tsabs, SEXP pBigMat, int nperm);
RcppExport SEXP aSPU2_calcT0Wsim3(SEXP CvSqrtSEXP, SEXP weightSEXP, SEXP powVSEXP, SEXP TsabsSEXP, SEXP pBigMatSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type CvSqrt(CvSqrtSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Tsabs(TsabsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calcT0Wsim3(CvSqrt, weight, powV, Tsabs, pBigMat, nperm));
    return rcpp_result_gen;
END_RCPP
}
// calcT0Wsim4
Rcpp::List calcT0Wsim4(arma::mat& CvSqrt, arma::mat& weight, arma::vec Tsabs, arma::vec powV, SEXP pBigMat, SEXP pBigMat3, int nperm);
RcppExport SEXP aSPU2_calcT0Wsim4(SEXP CvSqrtSEXP, SEXP weightSEXP, SEXP TsabsSEXP, SEXP powVSEXP, SEXP pBigMatSEXP, SEXP pBigMat3SEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type CvSqrt(CvSqrtSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Tsabs(TsabsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat3(pBigMat3SEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calcT0Wsim4(CvSqrt, weight, Tsabs, powV, pBigMat, pBigMat3, nperm));
    return rcpp_result_gen;
END_RCPP
}
// calcT0WsimV3
Rcpp::List calcT0WsimV3(arma::mat& CvSqrt, arma::mat& weight, arma::vec powV, SEXP pBigMat, SEXP pBigMat3, int nperm);
RcppExport SEXP aSPU2_calcT0WsimV3(SEXP CvSqrtSEXP, SEXP weightSEXP, SEXP powVSEXP, SEXP pBigMatSEXP, SEXP pBigMat3SEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type CvSqrt(CvSqrtSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat3(pBigMat3SEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calcT0WsimV3(CvSqrt, weight, powV, pBigMat, pBigMat3, nperm));
    return rcpp_result_gen;
END_RCPP
}
// calc_test_ch
void calc_test_ch(arma::mat& cov, arma::mat& weight, arma::vec powV, SEXP pBigMat, SEXP pBigMat2, int nperm);
RcppExport SEXP aSPU2_calc_test_ch(SEXP covSEXP, SEXP weightSEXP, SEXP powVSEXP, SEXP pBigMatSEXP, SEXP pBigMat2SEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat2(pBigMat2SEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    calc_test_ch(cov, weight, powV, pBigMat, pBigMat2, nperm);
    return R_NilValue;
END_RCPP
}
// calc_test_ch_V3
void calc_test_ch_V3(arma::mat& cov, arma::vec& mean, arma::mat& weight, arma::vec powV, SEXP pBigMat, SEXP pBigMat2, int nperm);
RcppExport SEXP aSPU2_calc_test_ch_V3(SEXP covSEXP, SEXP meanSEXP, SEXP weightSEXP, SEXP powVSEXP, SEXP pBigMatSEXP, SEXP pBigMat2SEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat2(pBigMat2SEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    calc_test_ch_V3(cov, mean, weight, powV, pBigMat, pBigMat2, nperm);
    return R_NilValue;
END_RCPP
}
// calc_test_pan
void calc_test_pan(arma::mat& cov, arma::mat& weight, arma::vec powV, SEXP pBigMat, SEXP pBigMat2, int nperm);
RcppExport SEXP aSPU2_calc_test_pan(SEXP covSEXP, SEXP weightSEXP, SEXP powVSEXP, SEXP pBigMatSEXP, SEXP pBigMat2SEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat2(pBigMat2SEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    calc_test_pan(cov, weight, powV, pBigMat, pBigMat2, nperm);
    return R_NilValue;
END_RCPP
}
// calc_test_ts
arma::mat calc_test_ts(arma::mat& cov, arma::mat& weight, arma::vec powV, arma::vec Ts);
RcppExport SEXP aSPU2_calc_test_ts(SEXP covSEXP, SEXP weightSEXP, SEXP powVSEXP, SEXP TsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Ts(TsSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_test_ts(cov, weight, powV, Ts));
    return rcpp_result_gen;
END_RCPP
}
// calc_test_ts_V3
arma::mat calc_test_ts_V3(arma::mat& cov, arma::vec& mean, arma::mat& weight, arma::vec powV, arma::vec Ts);
RcppExport SEXP aSPU2_calc_test_ts_V3(SEXP covSEXP, SEXP meanSEXP, SEXP weightSEXP, SEXP powVSEXP, SEXP TsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Ts(TsSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_test_ts_V3(cov, mean, weight, powV, Ts));
    return rcpp_result_gen;
END_RCPP
}
// calc_p_ch
Rcpp::List calc_p_ch(arma::vec powV, arma::vec Tsabs, SEXP pBigMat2, int nperm);
RcppExport SEXP aSPU2_calc_p_ch(SEXP powVSEXP, SEXP TsabsSEXP, SEXP pBigMat2SEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Tsabs(TsabsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat2(pBigMat2SEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_p_ch(powV, Tsabs, pBigMat2, nperm));
    return rcpp_result_gen;
END_RCPP
}
// calc_p_ch_pan
Rcpp::List calc_p_ch_pan(arma::vec powV, arma::vec Tsabs, SEXP pBigMat, int nperm);
RcppExport SEXP aSPU2_calc_p_ch_pan(SEXP powVSEXP, SEXP TsabsSEXP, SEXP pBigMatSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Tsabs(TsabsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_p_ch_pan(powV, Tsabs, pBigMat, nperm));
    return rcpp_result_gen;
END_RCPP
}
// calc_p_pan
Rcpp::List calc_p_pan(arma::vec Tsabs, SEXP pBigMat, SEXP pBigMat2, SEXP pBigMat3, int nTs, int nweight, int nperm);
RcppExport SEXP aSPU2_calc_p_pan(SEXP TsabsSEXP, SEXP pBigMatSEXP, SEXP pBigMat2SEXP, SEXP pBigMat3SEXP, SEXP nTsSEXP, SEXP nweightSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Tsabs(TsabsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat2(pBigMat2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat3(pBigMat3SEXP);
    Rcpp::traits::input_parameter< int >::type nTs(nTsSEXP);
    Rcpp::traits::input_parameter< int >::type nweight(nweightSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_p_pan(Tsabs, pBigMat, pBigMat2, pBigMat3, nTs, nweight, nperm));
    return rcpp_result_gen;
END_RCPP
}
// calc_aSPU
arma::vec calc_aSPU(arma::mat p_cov, SEXP pBigMat2, int nperm);
RcppExport SEXP aSPU2_calc_aSPU(SEXP p_covSEXP, SEXP pBigMat2SEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type p_cov(p_covSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat2(pBigMat2SEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_aSPU(p_cov, pBigMat2, nperm));
    return rcpp_result_gen;
END_RCPP
}
// daSPU_calcT0Wsim4
Rcpp::List daSPU_calcT0Wsim4(arma::mat& CvSqrt, arma::mat& weight, arma::vec powV, arma::vec Tsabs, SEXP pBigMat, SEXP pBigMat2, SEXP pBigMat3, int nperm);
RcppExport SEXP aSPU2_daSPU_calcT0Wsim4(SEXP CvSqrtSEXP, SEXP weightSEXP, SEXP powVSEXP, SEXP TsabsSEXP, SEXP pBigMatSEXP, SEXP pBigMat2SEXP, SEXP pBigMat3SEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type CvSqrt(CvSqrtSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Tsabs(TsabsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat2(pBigMat2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat3(pBigMat3SEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(daSPU_calcT0Wsim4(CvSqrt, weight, powV, Tsabs, pBigMat, pBigMat2, pBigMat3, nperm));
    return rcpp_result_gen;
END_RCPP
}
// daSPU_calc_aSPU
arma::vec daSPU_calc_aSPU(arma::mat p_cov, SEXP pBigMat2, int nperm);
RcppExport SEXP aSPU2_daSPU_calc_aSPU(SEXP p_covSEXP, SEXP pBigMat2SEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type p_cov(p_covSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat2(pBigMat2SEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(daSPU_calc_aSPU(p_cov, pBigMat2, nperm));
    return rcpp_result_gen;
END_RCPP
}
// calcT0Wsim2
Rcpp::List calcT0Wsim2(arma::mat& CvSqrt, arma::mat& weight, arma::vec pow1, arma::vec pow2, int nperm);
RcppExport SEXP aSPU2_calcT0Wsim2(SEXP CvSqrtSEXP, SEXP weightSEXP, SEXP pow1SEXP, SEXP pow2SEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type CvSqrt(CvSqrtSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pow1(pow1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pow2(pow2SEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calcT0Wsim2(CvSqrt, weight, pow1, pow2, nperm));
    return rcpp_result_gen;
END_RCPP
}
// daSPU_calcT0
arma::vec daSPU_calcT0(arma::mat& CvSqrt, arma::mat& weight, arma::vec pow1, arma::vec pow2, arma::vec Tsabs, SEXP pBigMat, int nperm);
RcppExport SEXP aSPU2_daSPU_calcT0(SEXP CvSqrtSEXP, SEXP weightSEXP, SEXP pow1SEXP, SEXP pow2SEXP, SEXP TsabsSEXP, SEXP pBigMatSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type CvSqrt(CvSqrtSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pow1(pow1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pow2(pow2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Tsabs(TsabsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(daSPU_calcT0(CvSqrt, weight, pow1, pow2, Tsabs, pBigMat, nperm));
    return rcpp_result_gen;
END_RCPP
}
